//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALSprint2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int ID { get; set; }
        public string Brand { get; set; }
        public string ModelName { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> SeatingCapacity { get; set; }
        public string CarStatus { get; set; }
        public string FuelType { get; set; }
        public Nullable<double> CarPricePerHour { get; set; }
    }
}
