//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALSprint2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string LicenseNumber { get; set; }
        public string UserPassword { get; set; }
        public Nullable<long> PhoneNumber { get; set; }
        public string Email { get; set; }
    }
}
