//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALSprint2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental
    {
        public int ID { get; set; }
        public Nullable<int> CarID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public Nullable<double> Price { get; set; }
        public string BookingStatus { get; set; }
    }
}
